apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  description: This task will run unit tests using the Jasmine framework.
  workspaces:
    - name: source
  steps:
    - name: unit-test
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Running Jasmine unit tests in $(workspaces.source.path) ..."
        npm test